### ISSUE TITLE
Cannot modify timestamp on Windows 10

### ISSUE THREAD

**Issue by chogys** [jschicht/SetMace#3]
I met "NtLoadDriver error" as belows on Windows 10.
But, it works well on Windows 7.

Does SetMace64.exe's NtLoadDriver not working on Windows 10?

---------------------------------------------------------------------------
D:\>SetMace.exe d:\stego.txt -c "2000:01:01:00:00:00:789:1234" -si
Starting SetMace by Joakim Schicht
Version 1.0.0.16

Target filename: stego.txt
Target fileref: 888
Target MFT record offset: 0x00000000C00DE000
Parent filename: .
Parent fileref: 5
Parent MFT record offset: 0x00000000C0001400

Start patching timestamps

Trying volume offset 0x00000000C00DE000
Error: NtLoadDriver: 0xC0000428
Error: Could not load driver
Attempting write to physical disk without driver
Error: You can't lock the volume that SetMace is run from

Patching resident INDX records of parent ($INDEX_ROOT)

Trying volume offset 0x00000000C0001400
Warning: The index in $INDEX_ROOT is not resident any more.

Patching non-resident INDX records of parent ($INDEX_ALLOCATION)

Trying volume offset 0x1E9D9000
Error: NtLoadDriver: 0xC0000428
Error: Could not load driver
Attempting write to physical disk without driver
Error: You can't lock the volume that SetMace is run from
Error: Ref 888 was found in this INDX record, but modification failed

File system cache cleared in RAM

Job took 3.32 seconds

**Comment by HennelovaZuzana** [comment]
How did you solve this problem?
